### ISSUE TITLE
Update link to new vm

### ISSUE THREAD

**Issue by Willow-Systems** [andyburris/pebble-setup#5]
Hey!

Thanks so much for writing this guide. I'll be sure to point people to it (and might even pull it in to help.rebble.io if you're okay with that?)

There's a newer VM based on Ubuntu 22.04 that was built for the hackathon. Could you please point people to that instead? It's available at https://rebble.io/hackathon-001/vm/

Thanks!

**Comment by andyburris** [comment]
Also I would definitely be ok with this being pulled into help.rebble.io, thank you!
